contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #genoflu-nf channel"
    url: https://nfcore.slack.com/channels/genoflu-nf
    about: Discussion about the BCCDC-PHL/genoflu-nf pipeline
